name: books
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  sqflite: ^2.3.3
  path: ^1.9.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  uuid: ^4.5.1
  shared_preferences: ^2.3.3
  flutter_quill: ^11.1.0
  flutter_quill_extensions: ^11.0.0
  intl: ^0.19.0
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  google_generative_ai: ^0.4.6
  markdown: ^7.3.0
  html: ^0.15.5
  flutter_launcher_icons: ^0.14.3
  turn_page_transition: ^0.4.0
  string_validator: ^1.1.0
  text_analysis: ^1.0.0+2
  flutter_rating_bar: ^4.0.1
  connectivity_plus: ^6.1.4

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - images/pluma.png
    - images/Designer.PNG
    - images/logo.png
